export const MY_EXPERIENCE = [
  {
    id: 1,
    value: 'freelance',
    logo: '',
    company: 'Freelance',
    role: '',
    date: '',
    firstDescription: '',
    tech: [
      {
        label: 'JS/TS',
        icon: '/logos/js-ts-logo.webp',
        alt: 'Javascript and Typescript logo',
      },
      { label: 'React', icon: '/logos/tag/react-logo.webp', alt: 'React logo' },
      { label: 'Node.js', icon: '/logos/node-js.webp', alt: 'Node logo' },
      {
        label: 'Next.js',
        icon: '/logos/tag/next-js.webp',
        alt: 'Next.js logo',
      },
      { label: 'Vite', icon: '/logos/vite-logo.webp', alt: 'Vite logo' },
      { label: 'Wagmi', icon: '/logos/tag/wagmi.webp', alt: 'Wagmi logo' },
      {
        label: 'Tailwind',
        icon: '/logos/tag/tailwind.webp',
        alt: 'Tailwind CSS logo',
      },
      {
        label: 'Prisma.io',
        icon: '/logos/tag/prisma-orm.webp',
        alt: 'Prisma ORM logo',
      },
      {
        label: 'MySQL',
        icon: '/logos/tag/mysql.webp',
        alt: 'Prisma ORM logo',
      },
    ],
    contributions: ['', '', '', '', ''],
  },
  {
    id: 1,
    value: 'fjord',
    logo: '',
    company: 'Fjord Foundry',
    role: '',
    date: '',
    firstDescription: '',
    tech: [
      {
        label: 'Next.js',
        icon: '/logos/tag/next-js.webp',
        alt: 'Next.js logo',
      },
      { label: 'Vite', icon: '/logos/vite-logo.webp', alt: 'Vite logo' },
      {
        label: 'Solidity',
        icon: '/logos/solidity-logo.webp',
        alt: 'Solidity logo',
      },
      {
        label: 'Solana',
        icon: '/logos/tag/solana-logo.webp',
        alt: 'Solana logo',
      },
      { label: 'React', icon: '/logos/tag/react-logo.webp', alt: 'React logo' },
      { label: 'Wagmi', icon: '/logos/tag/wagmi.webp', alt: 'Wagmi logo' },
      {
        label: 'Tailwind',
        icon: '/logos/tag/tailwind.webp',
        alt: 'Tailwind CSS logo',
      },
      {
        label: 'PlanetScale',
        icon: '/logos/tag/planet-scale.webp',
        alt: 'PlanetScale logo',
      },
      {
        label: 'Prisma.io',
        icon: '/logos/tag/prisma-orm.webp',
        alt: 'Prisma ORM logo',
      },
      { label: 'Docker', icon: '/logos/tag/docker.webp', alt: 'Docker logo' },
    ],
    contributions: [
      'Built reusable and accessible UI components and integrated them into the site.',
      'Built new pages and wired them up with backend data.',
      'Contributed to the development of the new website version (v4).',
      'Contributed to the integration of the Solana ecosystem.',
      'Improved performance and overall UX.',
    ],
  },
]
